name: Django CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Build Docker image
      run: docker build -t my-django-app .

    - name: Run Docker containers
      run: docker run -e DJANGO_SETTINGS_MODULE=bnmc.settings -p 8000:8000 my-django-app python manage.py runserver 0.0.0.0:8000

    - name: Run tests
      run: docker run my-django-app python manage.py test
